/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/9.4.0/samples
 */


plugins{
    application
}

repositories{
    mavenCentral()
}

dependencies{

}

application{
    mainClass="it.unicam.cs.mpgc.rpg129097.Prova"
}



